# Generated by Django 5.2.4 on 2025-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text_preview', models.TextField()),
                ('full_text', models.TextField()),
                ('analysis_type', models.CharField(choices=[('plagiarism', 'Plagiarism Detection'), ('ai-detection', 'AI Detection')], max_length=32)),
                ('result', models.CharField(max_length=64)),
                ('confidence', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('embedding', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
