# Generated by Django 4.2.7 on 2025-11-15 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_imageanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentForgery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_type', models.CharField(choices=[('forgery', 'Document Forgery Detection'), ('plagiarism', 'Document Plagiarism Detection'), ('ai-detection', 'Document AI Detection')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('document_text', models.TextField()),
                ('text_preview', models.TextField()),
                ('result', models.CharField(max_length=100)),
                ('confidence', models.IntegerField()),
                ('forgery_indicators', models.JSONField(blank=True, default=list)),
                ('technical_details', models.JSONField(blank=True, default=dict)),
                ('metadata_analysis', models.JSONField(blank=True, default=dict)),
                ('match_percent', models.IntegerField(default=0)),
                ('matched_document_id', models.IntegerField(blank=True, null=True)),
                ('matched_excerpt', models.TextField(blank=True)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Forgery Analysis',
                'verbose_name_plural': 'Document Forgery Analyses',
                'db_table': 'document_forgery',
                'ordering': ['-created_at'],
            },
        ),
    ]
