# Generated by Django 4.2.7 on 2025-11-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_documentforgery'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(db_index=True, max_length=256, unique=True)),
                ('verification_type', models.CharField(choices=[('hash', 'Hash Verification'), ('signature', 'Digital Signature'), ('blockchain', 'Blockchain Verification'), ('checksum', 'Checksum Verification')], default='hash', max_length=20)),
                ('verification_method', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('authentic', 'Authentic - Verified'), ('modified', 'Modified - Changes Detected'), ('corrupted', 'Corrupted - Data Integrity Failed'), ('unknown', 'Unknown - Unable to Verify')], default='unknown', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_authentic', models.BooleanField(default=False)),
                ('hash_comparison', models.JSONField(blank=True, default=dict)),
                ('signature_details', models.JSONField(blank=True, default=dict)),
                ('modification_details', models.JSONField(blank=True, default=list)),
                ('checksums', models.JSONField(blank=True, default=dict)),
                ('created_timestamp', models.DateTimeField(blank=True, null=True)),
                ('modified_timestamp', models.DateTimeField(blank=True, null=True)),
                ('accessed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('file_metadata', models.JSONField(blank=True, default=dict)),
                ('verification_history', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('technical_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_verification_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_verification', to='App.integritycheck')),
            ],
            options={
                'verbose_name': 'Integrity Check',
                'verbose_name_plural': 'Integrity Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrityCheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(blank=True, max_length=256)),
                ('current_hash', models.CharField(max_length=256)),
                ('change_detected', models.BooleanField(default=False)),
                ('change_details', models.JSONField(blank=True, default=dict)),
                ('modification_timestamp', models.DateTimeField(blank=True, null=True)),
                ('verification_result', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integrity_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='App.integritycheck')),
            ],
            options={
                'verbose_name': 'Integrity Check History',
                'verbose_name_plural': 'Integrity Check Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integritycheck',
            index=models.Index(fields=['file_hash'], name='App_integri_file_ha_acecc0_idx'),
        ),
        migrations.AddIndex(
            model_name='integritycheck',
            index=models.Index(fields=['verification_type'], name='App_integri_verific_47be29_idx'),
        ),
        migrations.AddIndex(
            model_name='integritycheck',
            index=models.Index(fields=['status'], name='App_integri_status_e4dd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='integritycheck',
            index=models.Index(fields=['-created_at'], name='App_integri_created_084d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='integritycheck',
            index=models.Index(fields=['result'], name='App_integri_result_70882b_idx'),
        ),
    ]
