# Generated by Django 4.2.7 on 2025-11-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_integritycheck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integritycheck',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
