# Generated by Django 4.2.7 on 2025-12-08 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0007_alter_integritycheck_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='textanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integritycheck',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
