# Generated by Django 4.2.7 on 2025-12-08 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0008_textanalysis_user_alter_integritycheck_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integritycheck',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='integritycheck',
            unique_together={('user', 'file_hash')},
        ),
    ]
