# -*- coding: utf-8 -*-
# Generated by Django X.X.X on YYYY-MM-DD HH:MM

from django.db import migrations, models  # Add models import here

def deduplicate_integritychecks(apps, schema_editor):
    IntegrityCheck = apps.get_model('App', 'IntegrityCheck')
    
    # Group by file_hash and keep the most recent record (latest created_at)
    # Or adjust criteria: e.g., keep by user if populated, or highest confidence
    duplicates = (
        IntegrityCheck.objects
        .values('file_hash')
        .annotate(max_id=models.Max('id'), count=models.Count('id'))
        .filter(count__gt=1)
    )
    
    for dup in duplicates:
        file_hash = dup['file_hash']
        max_id = dup['max_id']
        
        # Delete all except the one with max_id (most recent)
        IntegrityCheck.objects.filter(file_hash=file_hash).exclude(id=max_id).delete()
        print(f"Deduplicated {file_hash}: kept ID {max_id}, deleted {dup['count'] - 1} records")

def reverse_deduplicate(apps, schema_editor):
    # Optional: For reversibility, but hard to restore deleted data safely
    # You could raise NotImplementedError if not needed
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('App', '0007_alter_integritycheck_file_hash'),
    ]

    operations = [
        migrations.RunPython(deduplicate_integritychecks, reverse_deduplicate),
    ]