# Generated by Django 4.2.7 on 2025-12-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_integritycheck_file_hash_and_more'),
        ('App', '0010_auto_20251208_1332'),
    ]

    operations = [
    ]
