# Generated by Django 5.2.4 on 2025-12-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_merge_20251208_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='analysis_image',
            field=models.ImageField(blank=True, help_text='Visual analysis result with ELA, edges, and detection overlay', max_length=500, null=True, upload_to='image_analysis/results/%Y/%m/%d/'),
        ),
    ]
