# Generated by Django 4.2.7 on 2026-02-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0012_imageanalysis_analysis_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentforgery",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
    ]
